sudo: true
dist: xenial

language: python

cache:
  directories:
    - $HOME/.cache/pip

matrix:
  include:
    # CPython 3.7
    - python: 3.7
      env: TOXENV=py37-local
      stage: Client Tests
    - python: 3.7
      env: TOXENV=py37-integ
      stage: Client Tests
    - python: 3.7
      env: TOXENV=py37-examples
      stage: Client Tests
    # CPython 3.8
    - python: 3.8
      env: TOXENV=py38-local
      stage: Client Tests
    - python: 3.8
      env: TOXENV=py38-integ
      stage: Client Tests
    - python: 3.8
      env: TOXENV=py38-examples
      stage: Client Tests
    # Security
    - python: 3.7
      env: TOXENV=bandit
      stage: Static Checks
    # Linting
    - python: 3.7
      env: TOXENV=lint
      stage: Static Checks
    # MyPy
    # need to sort out some issues with optional values
    #- python: 3.7
    #  env: TOXENV=mypy
    #  stage: Static Checks

install: pip install tox
script: tox -- -vv
